my commit for HW5 Enum
Evgeniya1992N/OOPHomeworks pull request #1
Opened 2023-12-20 08:46 UTC by Evgeniya1992N

Check my HW5 Enum

2023-12-21 10:51 UTC, isavinov requested changes

2023-12-21 10:51 UTC, isavinov commented on src/transport/Car.java
> +               CarModel carModel) {
Вот тоже самое (Передача значения соотвествующего энама в конструктор) должно быть сделано и для классов Truck и Bus

2023-12-21 10:51 UTC, isavinov commented on src/transport/Transport.java
> +    public enum Type {
Вынеси этот энам в отдельный файл (так же, как и с классами делаешь)

2023-12-21 10:51 UTC, isavinov commented on src/transport/Transport.java
> +    public String getType(){
А этот сделай абстрактным
`public abstract Type getType();`
А в наследниках возвращай уже конкретный Type

2023-12-21 15:22 UTC, Evgeniya1992N commented on src/transport/Car.java
> +               CarModel carModel) {
Done:-)

2023-12-21 15:23 UTC, Evgeniya1992N commented on src/transport/Transport.java
> +    public enum Type {
Done:-)

2023-12-21 15:23 UTC, Evgeniya1992N commented on src/transport/Transport.java
> +    public String getType(){
Done:-)

2023-12-21 15:52 UTC, isavinov approved these changes

2023-12-21 15:52 UTC, isavinov commented on src/transport/Car.java
> +    public Type getType() {
Все проще
`return Type.CAR;`

2024-01-08 09:51 UTC, isavinov requested changes

2024-01-08 09:51 UTC, isavinov commented on src/transport/Transport.java
> +    public abstract void startMove() throws EmptyGasTankException, NoOilException;
Непроверяемые исключения не обязательно добавлять в сигнатуру метода, только проверяемые

2024-01-08 09:51 UTC, isavinov commented on src/transport/NoOilException.java
> +public class NoOilException extends IOException {
NoOilException так же должно быть непроверяемым.
(IOException == Input Output Exception, базовый класс для всех ошибок ввода/вывода, в этом эксепшене он неуместен)

2024-01-11 13:59 UTC, merged